# ################################
# Model: MossFormer for source separation
# Dataset : Aishell1mix2
# ################################
#
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data params

# this is the storage folder for the whole needed dataset e.g. /yourpath
# it should contain at least 250G space for aishell1, wham_noise and aishell1mix.
num_spks: 3
data_folder: !PLACEHOLDER
data_folder_nspks: !ref <data_folder>/aishell1mix/Aishell1Mix<num_spks>
data_freqs: ['8k'] # or if you want the whole dataset ['8k','16k']
data_modes: ['min'] # or if you want the whole dataset ['min', 'max']

# this is the base folder for dynamic mixing, usually not changed.
base_folder_dm: !ref <data_folder>/data_aishell/wav/train

experiment_name: mossformer-aishell1mix3
output_folder: !ref results/<experiment_name>/<seed>
train_log: !ref <output_folder>/train_log.txt
save_folder: !ref <output_folder>/save
train_data: !ref <save_folder>/aishell1mix3_train.csv
valid_data: !ref <save_folder>/aishell1mix3_dev.csv
test_data: !ref <save_folder>/aishell1mix3_test.csv
skip_prep: False

ckpt_interval_minutes: 60

# Experiment params
auto_mix_prec: True # Set it to True for mixed precision
noprogressbar: False
save_audio: False # Save estimated sources on disk
sample_rate: 8000

# Training parameters
N_epochs: 200
batch_size: 1
lr: 0.00015
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: False
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 32000000

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: True
use_wham_noise: False

# Parameters for data augmentation
use_wavedrop: False
use_speedperturb: True
use_rand_shift: False
min_shift: -8000
max_shift: 8000

speedperturb: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 1.0
    drop_freq_prob: 0.0
    drop_chunk_prob: 0.0
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 0.0
    drop_freq_prob: 1.0
    drop_chunk_prob: 1.0
    sample_rate: !ref <sample_rate>

# loss thresholding -- this thresholds the training loss
threshold_byloss: True
threshold: -30

# Encoder parameters
encoder_kernel_size: 16
encoder_out_nchannels: 512
encoder_in_nchannels: 1

masknet_numspks: !ref <num_spks>
masknet_chunksize: 250 #K
masknet_numlayers: 1
masknet_norm: "ln"
masknet_useextralinearlayer: False
masknet_extraskipconnection: True

intra_numlayers: 24
intra_nhead: 8
intra_dffn: 1024
intra_dropout: 0
intra_use_positional: True
intra_norm_before: True

# Dataloader options
dataloader_opts:
    batch_size: !ref <batch_size>
    num_workers: 4


# Specifying the network
Encoder: !new:speechbrain.lobes.models.mossformer.utils.one_path_flash_fsmn.Encoder
    kernel_size: !ref <encoder_kernel_size>
    out_channels: !ref <encoder_out_nchannels>
    in_channels: !ref <encoder_in_nchannels>


intra_model: !new:speechbrain.lobes.models.mossformer.utils.one_path_flash_fsmn.SBFLASHBlock_DualA
    num_layers: !ref <intra_numlayers>
    d_model: !ref <encoder_out_nchannels>
    nhead: !ref <intra_nhead>
    d_ffn: !ref <intra_dffn>
    dropout: !ref <intra_dropout>
    use_positional_encoding: !ref <intra_use_positional>
    norm_before: !ref <intra_norm_before>


MaskNet: !new:speechbrain.lobes.models.mossformer.utils.one_path_flash_fsmn.Dual_Path_Model
    in_channels: !ref <encoder_out_nchannels>
    out_channels: !ref <encoder_out_nchannels>
    intra_model: !ref <intra_model>
    num_layers: !ref <masknet_numlayers>
    norm: !ref <masknet_norm>
    K: !ref <masknet_chunksize>
    num_spks: !ref <masknet_numspks>
    skip_around_intra: !ref <masknet_extraskipconnection>
    linear_layer_after_inter_intra: !ref <masknet_useextralinearlayer>


Decoder: !new:speechbrain.lobes.models.mossformer.utils.one_path_flash_fsmn.Decoder
    in_channels: !ref <encoder_out_nchannels>
    out_channels: !ref <encoder_in_nchannels>
    kernel_size: !ref <encoder_kernel_size>
    stride: !ref <encoder_kernel_size> //2
    bias: False

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>
    weight_decay: 0

loss: !name:speechbrain.nnet.losses.get_si_snr_with_pitwrapper

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
    factor: 0.5
    patience: 2
    dont_halve_until_epoch: 5

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <N_epochs>

modules:
    encoder: !ref <Encoder>
    decoder: !ref <Decoder>
    masknet: !ref <MaskNet>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        encoder: !ref <Encoder>
        decoder: !ref <Decoder>
        masknet: !ref <MaskNet>
        counter: !ref <epoch_counter>
        # lr_scheduler: !ref <lr_scheduler>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

# If you do not want to use the pretrained separator you can simply delete pretrained_separator field.
#pretrained_separator: !new:speechbrain.utils.parameter_transfer.Pretrainer
#    collect_in: !ref <save_folder>
#    loadables:
#        encoder: !ref <Encoder>
#        decoder: !ref <Decoder>
#        masknet: !ref <MaskNet>
#    paths:
#        encoder: speechbrain/sepformer-wsj02mix/encoder.ckpt
#        decoder: speechbrain/sepformer-wsj02mix/decoder.ckpt
#        masknet: speechbrain/sepformer-wsj02mix/masknet.ckpt
